import { categoryLabel } from "@/lib/portfolio-categories";
import type { PortfolioCategory } from "@/generated/prisma/enums";

/**
 * Placeholder portfolio entries.
 *
 * A SINGLE SOURCE OF TRUTH, shared by three consumers that must never disagree:
 *
 *   1. `prisma/seed.ts`                      — the rows written to the database
 *   2. `scripts/generate-placeholders.ts`    — the placeholder cover artwork
 *   3. `src/content/services.ts`             — via `relatedProjectSlugs`
 *
 * These previously lived in two separate hardcoded lists joined only by a
 * "keep in sync" comment, which is exactly the kind of arrangement that rots:
 * rename a slug in one place and the service page silently loses its related
 * work while the seed and the artwork still use the old name. Sharing the
 * array makes that failure impossible, and
 * `src/content/__tests__/placeholder-projects.test.ts` asserts the
 * cross-references actually resolve.
 *
 * ---------------------------------------------------------------------------
 * THESE ARE PLACEHOLDERS, AND THE STRUCTURE IS DELIBERATE
 * ---------------------------------------------------------------------------
 * No real client has been named, no engagement has been claimed, and no
 * result, figure, percentage or measurement has been invented. Writing
 * plausible-looking case studies of work that has not happened would
 * misrepresent the company to the exact people it is trying to win.
 *
 * So every entry is built from two honest ingredients and nothing else:
 *
 *   `scenario` — the KIND of situation this entry stands in for. This is the
 *                list of problems a real engagement of this type typically
 *                starts with, taken from the service catalogue. It describes
 *                the work, not a client.
 *   `work`     — the KIND of work that situation usually involves.
 *
 * Everything else is generated by `toPlaceholderProject`, which stamps the
 * placeholder disclaimer onto all four prose fields. That is why the
 * disclaimer cannot be forgotten on one field of one entry, and why this file
 * stays reviewable: each line is either a slug, a title, a category, a
 * service reference or a sentence describing the shape of the work.
 *
 * Replace rows with real projects as they are supplied; no schema change is
 * needed. Drop the file into a real entry by setting `isPlaceholder: false` on
 * the database row and replacing the four prose fields.
 *
 * This module is deliberately free of database and framework imports so that
 * plain Node scripts can consume it. It imports only generated enums and one
 * pure helper.
 */
export type PlaceholderProject = {
  slug: string;
  title: string;
  category: PortfolioCategory;
  /** Links the entry back to a service in `src/content/services.ts`. */
  serviceSlug: string;
  summary: string;
  problem: string;
  solution: string;
  toolsUsed: string[];
  result: string;
  /** Path under `public/`, produced by `npm run placeholders`. */
  coverImage: string;
};

/** The parts of an entry that a human actually writes. */
type PlaceholderSeed = {
  slug: string;
  title: string;
  category: PortfolioCategory;
  serviceSlug: string;
  /** The kind of situation this entry stands in for. */
  scenario: string;
  /** The kind of work that situation usually involves. */
  work: string;
};

/**
 * Expands a seed into a full entry, applying the placeholder framing to every
 * prose field.
 *
 * `result` is identical across all entries on purpose. It is the one field
 * where variety would be most tempting and most dangerous — an invented
 * outcome is the easiest thing on this page for a visitor to read as a real
 * claim, and the hardest for them to spot as a placeholder.
 */
function toPlaceholderProject(seed: PlaceholderSeed): PlaceholderProject {
  const kind = categoryLabel(seed.category).toLowerCase();

  return {
    slug: seed.slug,
    title: seed.title,
    category: seed.category,
    serviceSlug: seed.serviceSlug,
    summary: `Sample ${kind} entry: ${seed.scenario}. Placeholder content — not a real project.`,
    problem: `Placeholder content. A real entry would open by summarising the situation the client actually presented. The kind of situation this entry stands in for: ${seed.scenario}.`,
    solution: `Placeholder content. A real entry would explain the approach taken, what was changed, and why it was chosen over the alternatives. The kind of work this entry stands in for: ${seed.work}.`,
    toolsUsed: ["[PLACEHOLDER: software, hardware and tools used]"],
    result: "Placeholder content. A real entry would state the outcome the client experienced. No client results or measurements have been supplied, and none have been invented.",
    coverImage: `/portfolio/${seed.slug}.svg`,
  };
}

/**
 * Three entries per service, so the portfolio grid reads as a real body of work
 * and so every category in the `/portfolio` filter has something to show.
 */
export const placeholderProjects: readonly PlaceholderProject[] = [
  // ---- Software maintenance -------------------------------------------
  toPlaceholderProject({
    slug: "placeholder-software-maintenance-slow-workstation",
    title: "Slow Workstation Restored",
    category: "SOFTWARE",
    serviceSlug: "software-maintenance",
    scenario: "a desktop that had become slow to start and unresponsive during everyday use",
    work: "diagnosing what had accumulated on the machine, clearing it out and correcting its configuration",
  }),
  toPlaceholderProject({
    slug: "placeholder-software-maintenance-update-failures",
    title: "Repeated Update Failures Resolved",
    category: "SOFTWARE",
    serviceSlug: "software-maintenance",
    scenario: "a work machine whose updates failed partway through and left it in an inconsistent state",
    work: "establishing what was blocking the updates, removing the conflict and applying them cleanly",
  }),
  toPlaceholderProject({
    slug: "placeholder-software-maintenance-app-reconfiguration",
    title: "Business Application Reconfigured",
    category: "SOFTWARE",
    serviceSlug: "software-maintenance",
    scenario: "an office application that stopped behaving correctly once the team and their permissions changed",
    work: "reviewing the configuration, correcting accounts and permissions, and checking the result with the people who use it",
  }),

  // ---- Software installation ------------------------------------------
  toPlaceholderProject({
    slug: "placeholder-software-installation-new-machine",
    title: "New Machine Prepared for Work",
    category: "SOFTWARE",
    serviceSlug: "software-installation",
    scenario: "a newly purchased computer that arrived with bundled trial software and no configuration",
    work: "installing and updating the operating system, removing the unwanted software and setting it up for daily use",
  }),
  toPlaceholderProject({
    slug: "placeholder-software-installation-device-drivers",
    title: "Printer and Scanner Set Up",
    category: "SOFTWARE",
    serviceSlug: "software-installation",
    scenario: "office hardware that would not work because the drivers were missing",
    work: "identifying the correct drivers, installing them and testing each device on the network",
  }),
  toPlaceholderProject({
    slug: "placeholder-software-installation-business-software",
    title: "Business Software Installed and Licensed",
    category: "SOFTWARE",
    serviceSlug: "software-installation",
    scenario: "software the business had paid for but could not get running",
    work: "installing it, working through the licensing, and connecting it to email and the network",
  }),

  // ---- Networking ------------------------------------------------------
  toPlaceholderProject({
    slug: "placeholder-networking-office-coverage",
    title: "Office Wi-Fi Coverage Improved",
    category: "NETWORKING",
    serviceSlug: "networking",
    scenario: "a wireless signal that did not reach reliably across the working area",
    work: "surveying the space, repositioning and reconfiguring the equipment and choosing better channels",
  }),
  toPlaceholderProject({
    slug: "placeholder-networking-shared-resources",
    title: "Shared Printing and Storage Set Up",
    category: "NETWORKING",
    serviceSlug: "networking",
    scenario: "a shared printer and shared storage that staff could not see on the network",
    work: "configuring the devices, the permissions and the addressing so everyone could reach them",
  }),
  toPlaceholderProject({
    slug: "placeholder-networking-guest-network",
    title: "Guest and Staff Networks Separated",
    category: "NETWORKING",
    serviceSlug: "networking",
    scenario: "visitor devices that needed internet access without being given access to the business network",
    work: "building a separate guest network and applying the access rules to it",
  }),

  // ---- Graphics design -------------------------------------------------
  toPlaceholderProject({
    slug: "placeholder-graphics-design-identity-basics",
    title: "Business Identity and Brand Basics",
    category: "GRAPHICS_DESIGN",
    serviceSlug: "graphics-design",
    scenario: "a business with no usable logo, no defined colours and no chosen typefaces",
    work: "designing an identity, fixing the colour palette and typography, and writing simple brand guidelines",
  }),
  toPlaceholderProject({
    slug: "placeholder-graphics-design-campaign-artwork",
    title: "Marketing Artwork for a Campaign",
    category: "GRAPHICS_DESIGN",
    serviceSlug: "graphics-design",
    scenario: "an event or promotion that needed artwork it did not yet have",
    work: "designing the artwork, adapting it to each format required and supplying print-ready files",
  }),
  toPlaceholderProject({
    slug: "placeholder-graphics-design-social-templates",
    title: "Social Media Template Set",
    category: "GRAPHICS_DESIGN",
    serviceSlug: "graphics-design",
    scenario: "posts that looked different every time because nothing had been defined",
    work: "producing a consistent template set and a short guide to using it correctly",
  }),

  // ---- Technology sales -------------------------------------------------
  toPlaceholderProject({
    slug: "placeholder-sales-office-workstations",
    title: "Office Workstation Supply",
    category: "COMPUTER_SERVICES",
    serviceSlug: "sales",
    scenario: "a set of machines needed for a team, with specifications that were hard to compare between sellers",
    work: "working out the actual requirement, recommending a specification and supplying a matched set",
  }),
  toPlaceholderProject({
    slug: "placeholder-sales-mobile-laptop",
    title: "Laptop Selected for Mobile Work",
    category: "COMPUTER_SERVICES",
    serviceSlug: "sales",
    scenario: "a machine that had to be carried between locations regularly",
    work: "matching weight, battery life and performance to how it would actually be used day to day",
  }),
  toPlaceholderProject({
    slug: "placeholder-sales-software-licensing",
    title: "Software Licensing for a Team",
    category: "COMPUTER_SERVICES",
    serviceSlug: "sales",
    scenario: "licences needed for several people at once, across more than one product",
    work: "identifying what was genuinely required, purchasing it and setting up the accounts",
  }),

  // ---- IT consultancy ---------------------------------------------------
  toPlaceholderProject({
    slug: "placeholder-consultancy-pre-purchase-review",
    title: "Pre-Purchase Technology Review",
    category: "OTHER",
    serviceSlug: "consultancy",
    scenario: "a significant purchase decision about to be made without independent advice",
    work: "reviewing the requirement and the competing options, then writing a recommendation",
  }),
  toPlaceholderProject({
    slug: "placeholder-consultancy-setup-review",
    title: "Review of an Existing Installation",
    category: "OTHER",
    serviceSlug: "consultancy",
    scenario: "a setup that had not delivered what it was supposed to",
    work: "examining what was actually in place, identifying the gaps and recommending what to change",
  }),
  toPlaceholderProject({
    slug: "placeholder-consultancy-growth-planning",
    title: "Systems Planning for Growth",
    category: "OTHER",
    serviceSlug: "consultancy",
    scenario: "a growing business that needed to know what to change before it became a problem",
    work: "assessing the current systems, data and connectivity, and proposing a staged plan",
  }),
];
